### PR TITLE
Fix #2 - check against total, not width

### LINKED ISSUE #2: Always creates 2 bars (Windows msys2, CentOS 7.4)
I recreated the demo, but I always get 2 bars, perhaps related to the extra printing of a '%' symbol?

```
[================================================.....................] 69.00%%
[=====================================================================>] 100.00%
```

nim v 0.19.4 installed progress via nimble

### PR DESCRIPTION
**Pull request by euantorano**
Should fix #2 

Tested on Mac so far, will test against Windows tomorrow as I have easy access to that. @JorySchossau any chance you could try this and see if it resolves your issue?

### CODE REVIEW

**Comment by JorySchossau** [comment]
Fixes CentOS for me!
Also fixed for MSYS2 if I use the winpty helper utility `winpty ./test.exe`. Without it, I think it's just not getting the terminal width correct, and always assumes 80 cols.

**Comment by euantorano** [comment]
Yeah, that sounds about right. I’ve never tried msys2 before, but I’ll try installing it on my work machine which is Windows 10 and try it there. I’ll merge this PR in the mean time and tag a new version though.

**Comment by JorySchossau** [comment]
mintty/MSYS2 terminal width inspection won't work - so don't worry about it. Thanks for fixing that so quickly!

**Comment by euantorano** [comment]
Ok, I'm pushing a new release now 😄

**Pull request merged**
